study_words_app/urls.py
from django.urls import path
from . import views
app_name = 'base_app'

urlpatterns = [
    path('add_new_words/', views.add_new_words, name='add_new_words'),
    path('word_added_successfully/', views.word_added_successfully, name='word_added_successfully'),
    path('table_of_words/', views.table_of_words, name='table_of_words'),
    path('flash_cards/', views.flash_cards, name='flash_cards'),
    path('main_training_page/', views.main_training_page, name='main_training_page'),
    path('training_en/', views.training_english_word, name='training_english_word'),
    path('training_ua/', views.training_ukrainian_word, name='training_ukrainian_word'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('registration.urls')),
	path('study_words/', include('study_words_app.urls')),
    path('admin/', admin.site.urls),
]

study_words_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Words(models.Model):
    en_word = models.CharField(max_length=16)
    ua_word = models.CharField(max_length=16)
    added_data = models.DateField(auto_now_add=True, blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.en_word, self.ua_word)

study_words_app/forms.py
from django import forms
from .models import Words


class WordsForm(forms.ModelForm):
    class Meta:
        model = Words
        fields = ['en_word', 'ua_word']
        labels = {
            "en_word": "Слово Aнглійською",
            "ua_word": "Переклад"
        }

        widgets = {
            'en_word': forms.TextInput(),
            'ua_word': forms.TextInput(),
        }

class DeleteForm(forms.Form):
    delete_word = forms.CharField(label='Enter any word you want to delete', max_length=16)

study_words_app/views.py
"""ADD WORDS, TABLE AND DELETING WORDS BLOCK"""

from random import shuffle
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import WordsForm, DeleteForm
from .models import Words


@login_required
def add_new_words(request):
    """Function get from the user data of new English and Ukrainian words,
     and write them in db. Also doing some validation of this data, and
     return error message when data is not valid"""
    if request.method == 'POST':
        form = WordsForm(request.POST)
        en = request.POST['en_word']
        ua = request.POST['ua_word']
        if form.is_valid() and (en.isalpha() and ua.isalpha()):
            en_word = form.cleaned_data['en_word'].capitalize()
            ua_word = form.cleaned_data['ua_word'].capitalize()
            form = WordsForm({'en_word': en_word, 'ua_word': ua_word}) #form = WordsForm(request.POST)
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('base_app:word_added_successfully')  # always must be redirect
        else:
            form = WordsForm()
            error_message = True
            return render(request, 'base_app/add_new_words.html', {'form': form, 'error_message': error_message})
    else:
        form = WordsForm()
    return render(request, 'base_app/add_new_words.html', {'form': form})


def word_added_successfully(request):
    """Function return success page, when forms in function add_new_words we get new data
    and error message when count of words less than 5 """

    words_list = list(Words.objects.filter(author_id=logged_in_user_id(request)).order_by('-id')[:10])
    error_not_enough_words = True
    if len(words_list) > 4:
        error_not_enough_words = False
    return render(request, 'base_app/word_added_successfully.html', {'error_not_enough_words': error_not_enough_words})


def logged_in_user_id(request):
    """"Function used in table_of_words()
    checks whether the user is authenticated and if so, returns his id"""

    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.id
    return user_id


def table_of_words(request):
    """Function return data from model into table
    and works with DeleteForm for deleting record from table"""

    fields = Words.objects.filter(author_id=logged_in_user_id(request)).order_by('-id')
    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            word = request.POST.get('delete_word', 'error')
            if word:
                Words.objects.filter(en_word=word).delete()
                Words.objects.filter(ua_word=word).delete()
            data = {'form': form, 'fields': fields}
            return render(request, 'base_app/table_of_words.html', data)
    else:
        form = DeleteForm()
    data = {'form': form, 'fields': fields}
    return render(request, 'base_app/table_of_words.html', data)


""" ---------- TRAINING BLOCK ------------- """


def main_training_page(request):
    """Call the main navigation page of training block"""
    return render(request, 'base_app/main_training_page.html')


def flash_cards(request):
    """Passes english words and translation into flashcard training page"""

    fields = Words.objects.filter(author_id=logged_in_user_id(request)).order_by('-id')[:8]
    return render(request, 'base_app/flash_cards.html', {'fields': fields})



def list_last5_from_table(request):
    """Returns list of last 5 records in db in format [['en_w','ua_word'],[...]]
    this function for using in training func"""

    query = list(Words.objects.filter(author_id=logged_in_user_id(request)).order_by('-id')[:5])
    return [str(items).split(' ') for items in query ]


en_word_index = 0  # variable for counting right answers
@login_required
def training_english_word(request):
    """The function is designed to run the training_ua.html page.
    Used dictionaries (keys(eng_word) -> value(ukr_word)) logic when it is compared whether the answer is correct"""

    all_words = {key: value for (key, value) in list_last5_from_table(request)}
    list_of_en_words = [en for en, ua in all_words.items()]
    list_of_ua_words = [ua for en, ua in all_words.items()]
    shuffle(list_of_ua_words)

    user_choice = ''
    if request.method == 'POST':
        d = dict(request.POST)
        for k, v in d.items():
            user_choice = v[0]   # return word selected by user from radio button form

    global en_word_index
    question_word = list_of_en_words[en_word_index]
    result = ''
    next = False
    if request.method == 'POST':
        if all_words[question_word] == user_choice:
            result = list_of_en_words[en_word_index] + " --> " + user_choice
            next = True
        else:
            result = "Wrong"

    if en_word_index >= 4:
        en_word_index = 0
        return redirect('base_app:main_training_page')
    elif next:
        en_word_index += 1
        question_word = list_of_en_words[en_word_index]

    data = {
        'result': result,
        'list_of_words': list_of_ua_words,
        "question_word": question_word,
    }
    return render(request, 'base_app/training_en.html', data)


ua_word_index = 0 # variable for counting right answers

@login_required
def training_ukrainian_word(request):
    """The function is designed to run the training_ua.html page.
    Used dictionaries (keys(ukr_word) -> value(eng_word)) logic when it is compared whether the answer is correct"""

    all_words = {value: key for (key, value) in list_last5_from_table(request)}
    list_of_ua_words = [en for en, ua in all_words.items()]
    list_of_en_words = [ua for en, ua in all_words.items()]
    shuffle(list_of_en_words)

    user_choice = ''
    if request.method == 'POST':
        d = dict(request.POST)
        for k, v in d.items():
            user_choice = v[0]   # return word selected by user from radio button form

    global ua_word_index
    question_word = list_of_ua_words[ua_word_index]
    result = ''
    next = False
    if request.method == 'POST':
        if all_words[question_word] == user_choice:
            result = list_of_ua_words[ua_word_index] + " --> " + user_choice
            next = True
        else:
            result = "Wrong"

    if ua_word_index >= 4:
        ua_word_index = 0
        return redirect('base_app:main_training_page')
    elif next:
        ua_word_index += 1
        question_word = list_of_ua_words[ua_word_index]

    data = {
        'result': result,
        'list_of_words': list_of_en_words,
        "question_word": question_word,
    }
    return render(request, 'base_app/training_ua.html', data)

study_words_app/templates/base_app/add_new_words.html
{% extends 'registration/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <h1>Add new words</h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy  }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">Add word</button>
                        </div>
                        <div class="text-center mt-3">
                            {% if error_message %}
                                <h4 style="color: red;"> Enter words only with letters, without numbers and other characters !</h4>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

study_words_app/templates/base_app/flash_cards.html
{% extends 'registration/base.html' %}
{% block content %}

<div class="content">
{% for f in fields %}
	<div class="flex-block">
		<div class='maincontainer'>
			<div class='thecard'>
				<div class="thefront">
					<h1>{{ f.en_word }}</h1>
				</div>
				<div class="theback">
					<h1>{{ f.ua_word }}</h1>
				</div>
			</div>
		</div>
	</div>
{% endfor %}
</div>
{% endblock%}

study_words_app/templates/base_app/main_training_page.html
{% extends 'registration/base.html' %}
{% block content %}

<h3>Main training page</h3>
<h4>Select type of training:</h4>
<ul>
    <a class="nav-link" href="{% url 'base_app:flash_cards' %}">Flash cards</a>
    <a class="nav-link" href="{% url 'base_app:training_english_word' %}"> English last 5 </a>
    <a class="nav-link" href="{% url 'base_app:training_ukrainian_word' %}"> Ukrainian last 5 </a>
</ul>

{% endblock%}

study_words_app/templates/base_app/table_of_words.html
{% extends 'registration/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="d-flex flex-wrap">
    <div class="col-8">
    <div class="table-wrapper-scroll-y">
      <table class="table table-bordered table-striped">
        <thead>
          <tr class="table-success">
            <th scope="col">№</th>
            <th scope="col">Слово</th>
            <th scope="col">Переклад</th>
            <th scope="col">Додано</th>
          </tr>
        </thead>
        <tbody>
           {% for item in fields %}
          <tr>
            <td>{{ forloop.revcounter }}</td>
            <td>{{ item.en_word }}</td>
            <td>{{ item.ua_word }}</td>
            <td>{{ item.added_data }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </div>
    </div>
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <h3 >Delete word</h3>
                </div>
                <div class="text-center">
                    <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                        <button type="submit" class="btn btn-success"> Delete </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

study_words_app/templates/base_app/test.html
{% extends 'registration/base.html' %}
{% block content %}



{% endblock%}

study_words_app/templates/base_app/training_en.html
{% extends 'registration/base.html' %}
{% block content %}

<div class="choice_block">
	<div class='answer_block'>
		<h1> Translate this word: {{ question_word }}</h1>
		<form action="" method="post">
			{% csrf_token %}
			{% for word in list_of_words %}
			<ul class="nav nav-tabs">
	       		<li class="nav-item" >
	          		<input type="radio" name="process" value="{{ word }}" id="{{ word }}"/>
					<label class="choice"> {{ word }} </label>
	        	</li>
	        </ul>
			</br>
			{% endfor %}
			<button type="submit" class="btn btn-success"> Answer </button>
		</form>
		{% if result %}
		<h2> {{ result }}</h2>
		{% else %}
		<h2>{{ result }}</h2>
		{% endif %}
	</div>
</div>

{% endblock%}

study_words_app/templates/base_app/training_ua.html
{% extends 'registration/base.html' %}
{% block content %}

<div class="choice_block">
	<div class='answer_block'>
		<h1> Translate this word: {{ question_word }}</h1>
		<form action="" method="post">
			{% csrf_token %}
			{% for word in list_of_words %}
			<ul class="nav nav-tabs">
	       		<li class="nav-item" >
	          		<input type="radio" name="process" value="{{ word }}" id="{{ word }}"/>
					<label class="choice"> {{ word }} </label>
	        	</li>
	        </ul>
			</br>
			{% endfor %}
			<button type="submit" class="btn btn-success"> Answer </button>
		</form>
		{% if result %}
		<h2> {{ result }}</h2>
		{% else %}
		<h2>{{ result }}</h2>
		{% endif %}
	</div>
</div>

{% endblock%}

study_words_app/templates/base_app/word_added_successfully.html
{% extends 'registration/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <h1>Words added successfully</h1>
    </div>
    <div class="row justify-content-center">
        {%  if error_not_enough_words %}
            <h4 style="color: red;">*Для початку вивчення додайте перших <strong>пять</strong> слів</h4>
        {% endif %}
    </div>
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="card-body text-center">
                <a href="{% url 'base_app:add_new_words' %}">
                    <button type="submit" class="btn btn-success mr-3"> Add new word </button>
                </a>
                <a href="{% url 'base_app:main_training_page' %}">
                    <button type="submit" class="btn btn-success mr-3"> Go training </button>
                </a>
                <a href="{% url 'base_app:table_of_words' %}">
                    <button type="submit" class="btn btn-success"> Table of words </button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock%}